[package]
name = "outer-frontiers"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Stepan Kizim <stsiapan.kizim@gmail.com>"]
edition = "2021"

# Enable max optimizations for dependencies, making debug build mach faster
[profile.dev.package."*"]
opt-level = 3

[dependencies]
# Keep only what is really used to keep binary small and compilation fast
bevy = { version = "0.11.2", default-features = false, features = [
  # Core 3D features
  "bevy_core_pipeline",
  "bevy_pbr",
  "bevy_render",
  "bevy_winit",
  "multi-threaded",
  # For skybox compressed texture
  "ktx2",
  "zstd",
  # For gltf assets
  "bevy_gltf",
  "tonemapping_luts", # for correct material loading

  "webgl2", # For wasm target
  # Might be used in the future
  # "wayland", # For linux support on CI
  # Other
  # "bevy_audio",
  # "bevy_text",
  # "bevy_ui",
  # "default_font",
] }
bevy-inspector-egui = "0.19"
bevy_asset_loader = "0.17"
# Check performance with "simd-stable" or "parallel"
bevy_rapier3d = { version = "0.22.0", default-features = false, features = ["dim3", "debug-render-3d"]}
# bevy_common_assets = "0.7" # for loading assets from yaml/json

# Using fork with backported https://github.com/bevyengine/bevy/pull/9909 to 0.11.2
# This allows us to use thirdparty plugins as the upstream is now on 0.12-dev
# Unfortunately patch works on per-crate basis, so we need to override all of them =\
[patch.crates-io]
bevy = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_app = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_asset = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_core = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_core_pipeline = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_ecs = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_hierarchy = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_log = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_math = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_pbr = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_reflect = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_render = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_utils = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
bevy_window = { git = "https://github.com/kinkard/bevy.git", branch = "v0.11.2-skybox-fix"}
